# Step 1 — Build the app using Maven
FROM maven:3.9.4-eclipse-temurin-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean install -DskipTests

# Step 2 — Run the app using Java 17
FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/target/stu-manage-cloud-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]